language: node_js

node_js:
  - "stable"

notifications:
  slack:
    secure: V1juhiQ2aw4Snpxv9VK25ANhs0Gq/jUJs3mPhhgobUw/J9ClN5ynFhOALzYiY2+dFAo2eyL1lGGkFhDxfw2suQwqqaylT9k5Jm7TKDdntbbBHleElCZzEuJuWMQwK3bfezCAQCp8LdGhAhHy9RvUgW9Nvve2L/K/Yp1f7ZQiH/9XjardjmDM98PWKVLBpuUMDubxcm/FXIxNw8e52FLQJ4DKDjzgqTsUUmF1w6TZbdkZJ+/CFTxnICbFX80g4ycKDdnyrf9KPDtP5OSkK7wDP2LnMbMwZWSRPinMjKMDG8E19LwoASRfywYusYgcm7STtXKi3jAsjOIZnuzA15jZpDO4lrJBAuUtv3AjpU4gX2wbGnd9U70KXfhG2iYBXQO8a+eQRgfVupxJqc2Eaj5cGEtQpLpRxB++yWeC5RXa11aR1ODn07GYs3iEWTaLXva0JVg8JnS0a1ToBC5xETZDr8DKNyTQAdszsTgdcZgCkATEyNS0y5L9I3cTiyXJg4KGHETmUmV3E0H5RL2Ml6jD5QYNEac+wNkvFHVqfJHV+ee+rJKXhmOIoaEyhyetrDgYTM/5hVzuyTgqhQDo9v33GN+DTPYfNsZam79xHKIyYQt9quOaXWGyOLIZ1e3SJ+RNRtdcnUAB+hGCaM92cRe+fy9n+fjE2ze+Auke0GY0tWg=
    # archesproject:
    secure: wy5F0B1zYZYWNaca2if3mxFuaa/bgbbcLPcK5BFt6haPxhWF1tqvglDQqUJ4kg+12LREmv644JbytuCAGYpZxjdbiu30wyrcVxIJUmin8rNQRSujlzAVooLRwT1+MPF8cNrJ2/TNYNv8yrUAq1kLgwLd+JioCZ7POVmxsZQenYGdE+U9CXEEpfy7/HUlrvYu+0L/Bb1iNstoQkqzpg35+layhkaAdZXPp12eEgeXdY7GYgvxf9GZ/ZEeCcLgDLZ2tTp26rApfZxoUWIhWipbBLX/dncQutCrQii0liOLcjroQ4Zx3yM6Hb/EggbrrhhqBlOBSWIpG5SI/5rFmQGDe9IGcbgUGuRIY8wdhQdVx4EX2nKCnW+SyHQAX9xsNVjOZxHMxbeyndIAPAFexxj13CVD6vJ6SuSke4ktVenOooPjdf3Znx7ZnDeFPyiD1XVEwbeVLleCKnwVLjgYdtipI5KKOybwoyKTvm3h4MgXEanmbkYqczfNXnBMvLeuc581RjcegQkK25X18l0oIKDIpcgcHV9KKCN5YmS3D5rigs61m6MPJKM65VjUC0+9ChuyWZPgmdFPkcXyzBlCfw3ZqjMrvglOLVJkjR16DJDdy58QtaASm3MujBpUjG/8db0rhqYSSbUm9dAo/Ya27D2P3U3SG9MRh+0vDNk+2pjqoDQ=

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
