language: node_js
node_js:
  - "stable"
notifications:
  slack:
    secure: TU++O0tP61TRz/dC/hOiZk9FoML7tdjHm4SqhQ6XWl+um9OcwOqcXYmAbDOwvSvioAlLHoZM/fbKi2DgpDHTLKPT156zsFvN75p6A494OV7tUzQ26RiUowsDZy5noGf+Pv2fLAfgeB8yA/3gbzVlzXrTTOjwhjvhilTNLXUMC+rZfhcA5Bl44pnDELJHAtPGOJFZwrW/eGFP+zDvW+s0AKoiKU5LECIG+ujv7pfmBarhxMHcdtrpw9KiII+BY6urZIDGQXuNjnLNIWEEriIwE+FC3UHBip5zjTIn6FuGEzw4OTQXhsBRPyrAYsA24WoXcQlojOltmWE1whUu+vCN4o5KFnOZrgrTqECZCVz4JK54a+ybJxniNPbPTfYAzlz6i6UsrrxIk7+oMY3NN03hfFyIeMBBMQz7cFuzsWUkU/vK9YML4ZbWG/Fk5TfQy3lwp5S1l2kshzSKCdfCtKbtpOKdvcCbAm5Q0BALIL2KWX2/lVqCeiEXgrVpYfiJJbaxxqJ0TY8e3HmIR64z3ohNlhq0LooPQmxGcsCC0gshgmDE/aju5gB6wSkLk5Sti8fxk3/nssxAskaYmgrj882jD+v9umCfxhJ19PqnEecQYuooKOm90UpOrt2dBnMosV3YNs65HGI9mKmMQpFk4NRxmxVtC1NSegVV9jQN/OTsZwE=
